# --- Background ---
background {
    monitor =
    path = $HOME/.config/hypr/wallpaper_effects/.wallpaper_current
    blur_size = 5
    blur_passes = 2       # 0 disables blurring
    noise = 0.1
    contrast = 1.3000     # Vibrant!
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

# --- Input Field ---
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.33        # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.15     # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    dots_rounding = -1      # -1 default circle, -2 follow input-field rounding
    outer_color = rgb(0c84b0)
    inner_color = rgb(FFFFFF)
    font_color = rgb(10, 10, 10)
    fade_on_empty = true
    fade_timeout = 1000     # Milliseconds before fade_on_empty is triggered
    placeholder_text = <i>Input Password...</i>
    hide_input = false
    rounding = -1           # -1 means complete rounding (circle/oval)
    check_color = rgb(204, 136, 34)
    fail_color = rgb(204, 34, 34)   # Outer + message color on failed auth
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300   # Transition time (ms) between outer_color and fail_color
    position = 0, -20
    halign = center
    valign = center
}

# --- Clock ---
label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = rgba(200, 200, 200, 1.0)
    font_size = 55
    font_family = Fira Semibold
    position = -100, 70
    halign = right
    valign = bottom
    shadow_passes = 5
    shadow_size = 10
}

# --- User ---
label {
    monitor =
    text = $USER
    color = rgba(200, 200, 200, 1.0)
    font_size = 20
    font_family = Fira Semibold
    position = -100, 160
    halign = right
    valign = bottom
    shadow_passes = 5
    shadow_size = 10
}

# --- Avatar ---
image {
    monitor =
    path = $HOME/.config/hypr/wallpaper_effects/.wallpaper_square
    size = 300              # Lesser side if not 1:1 ratio
    rounding = -1           # Negative values mean circle
    border_size = 4
    border_color = rgb(221, 221, 221)
    rotate = 0              # Degrees, counter-clockwise
    reload_time = -1
    position = 0, 200
    halign = center
    valign = center
}
