$background = rgb(1B1B25)
$foreground = rgb(EFDCEE)
$color0 = rgb(42424C)
$color1 = rgb(52314B)
$color2 = rgb(453D62)
$color3 = rgb(2F4677)
$color4 = rgb(655482)
$color5 = rgb(765C81)
$color6 = rgb(9D749A)
$color7 = rgb(E0C5DE)
$color8 = rgb(9C8A9B)
$color9 = rgb(6D4164)
$color10 = rgb(5C5282)
$color11 = rgb(3F5E9F)
$color12 = rgb(8770AD)
$color13 = rgb(9D7BAC)
$color14 = rgb(D19BCD)
$color15 = rgb(E0C5DE)
