source = $HOME/.config/hypr/wallust/wallust-hyprland.conf

# --- General Layout & Appearance ---
general {
    border_size = 0
    gaps_in = 6
    gaps_out = 8

    resize_on_border = true

    col.active_border = $color12
    col.inactive_border = $background

    no_focus_fallback = true
    layout = dwindle

    # NVIDIA: tearing allows lower latency (VSync off) but may cause visual tearing.
    allow_tearing = false
}

# --- Layouts (Dwindle & Master) ---
dwindle {
    preserve_split = yes
    special_scale_factor = 0.8
}

master {
    new_status = master
    new_on_top = 1
    mfact = 0.5
}

# --- Groups ---
group {
    col.border_active = $color15
    groupbar {
        col.active = $color0
    }
}

# --- Input & Peripherals ---
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    repeat_rate = 50
    repeat_delay = 300

    sensitivity = +0.5
    numlock_by_default = true
    left_handed = false
    follow_mouse = true
    float_switch_override_focus = false

    touchpad {
        disable_while_typing = true
        natural_scroll = true
        clickfinger_behavior = false
        middle_button_emulation = true
        tap-to-click = true
        drag_lock = false
        scroll_factor = 0.4
    }
}

device {
    name = hp-omen-vector-wireless-mouse-dongle
    sensitivity = 1
}

# --- Miscellaneous ---
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    vrr = 1
    mouse_move_enables_dpms = true
    enable_swallow = true
    swallow_regex = ^(kitty)$
    focus_on_activate = false
    initial_workspace_tracking = 0
    middle_click_paste = false
    on_focus_under_fullscreen = 1
    exit_window_retains_fullscreen = true
}

# --- Binds ---
binds {
    allow_workspace_cycles = true
    pass_mouse_when_bound = false
}

# --- XWayland ---
xwayland {
    force_zero_scaling = true
}

# --- Rendering ---
render {
    # Set to true only if you want to risk visual glitches for 1ms lower latency
    direct_scanout = false
}

# --- Cursor ---
cursor {
    no_hardware_cursors = false
    enable_hyprcursor = true
    warp_on_change_workspace = true
    no_warps = true
}
