# --- Settings Tags ---
windowrule = match:title (Kvantum Manager), tag +settings
windowrule = match:class ^(nm-applet|nm-connection-editor|blueman-manager)$, tag +settings
windowrule = match:class ^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$, tag +settings
windowrule = match:class ^(qt5ct|qt6ct)$, tag +settings
windowrule = match:class (xdg-desktop-portal-gtk), tag +settings
windowrule = match:class ^(org.kde.polkit-kde-authentication-agent-1)$, tag +settings
windowrule = match:class ^([Rr]ofi)$, tag +settings
windowrule = match:class ^(btrfs-assistant)$, tag +settings
windowrule = match:class ^(timeshift-gtk)$, tag +settings

# --- Idle Inhibit ---
# Prevent idle while a fullscreen app is focused
windowrule = match:fullscreen true, idle_inhibit fullscreen

# --- Float ---
windowrule = match:tag settings, float on, center on
windowrule = match:class ^([Tt]hunar)$, float on, size (monitor_w*0.7) (monitor_h*0.6), center on
windowrule = match:title ^(Authentication Required)$, float on, center on
windowrule = match:title ^(Add Folder to Workspace)$, float on, size (monitor_w*0.7) (monitor_h*0.6), center on
windowrule = match:title ^(Save As)$, float on, size (monitor_w*0.7) (monitor_h*0.6), center on
windowrule = match:initial_title ^(Open Files)$, float on, size (monitor_w*0.7) (monitor_h*0.6), center on

# --- Emulator ---
windowrule {
    name = Emulator
    match:title = ^(Emulator)$
    float = on
    suppress_event = maximize
    keep_aspect_ratio = on
    center = on
}

# --- Picture-in-Picture ---
windowrule {
    name = Picture-in-Picture
    match:title = ^(Picture-in-Picture)$
    float = on
    move = 72% 7%
    opacity = 0.95 0.75
    pin = on
    keep_aspect_ratio = on
    size = (monitor_w*0.3) (monitor_h*0.3)
}

# --- Thunar Copy Progress Dialog ---
windowrule {
    name = Thunar-Progress-bar
    match:class = ^(thunar)$
    match:title = ^(File Operation Progress)$
    float = on
    center = on
    size = (monitor_w*0.26) (monitor_h*0.18)
}
